const UserActionTypes = {
    REGISTER_USER: 'REGISTER_USER',
    SIGNIN_USER: 'SIGNIN_USER',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    UPDATE_LAST_INVOICE_NUMBER: 'UPDATE_LAST_INVOICE_NUMBER',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default UserActionTypes;