const InvoiceActionTypes = {
    SET_INVOICES: 'SET_INVOICES',
    ADD_OR_UPDATE_INVOICES: 'ADD_OR_UPDATE_INVOICES',
    DELETE_INVOICE: 'DELETE_INVOICE',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default InvoiceActionTypes;