const CustomerActionTypes = {
    SET_CUSTOMERS: 'SET_CUSTOMERS',
    SET_CUSTOMER_GROUPS: 'SET_CUSTOMER_GROUPS',
    ADD_OR_UPDATE_CUSTOMERS: 'ADD_OR_UPDATE_CUSTOMERS',
    SET_SELECTED_CUSTOMER: 'SELECT_SELECTED_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default CustomerActionTypes;